Fix build requirement in sed when installing in CentOS
rdo-common/openvswitch pull request #7
Opened 2018-02-17 15:17 UTC by amoralej

When installing openvswitch in a empty buildroot or a system which
doesn't have sed installed, it fails with error:

Error: Package: 1:openvswitch-2.8.1-5.1fc28.el7.x86_64 (delorean-queens-testing)
           Requires: /usr/bin/sed

As sed package in CentOS has not "/usr/bin/sed" in the list of provides:

bundled(gnulib)
sed = 4.2.2-5.el7
sed(x86-64) = 4.2.2-5.el7

This patch changes de BuildRequires from /usr/bin/sed file to sed
package.

2018-02-19 21:48 UTC, apevec commented
> has not "/usr/bin/sed" in the list of provides
This is actually coming from the list of files and RHEL7 is pre-move-to-/usr so sed is in /bin/sed
It was fixed in the internal build https://bugzilla.redhat.com/show_bug.cgi?id=1506245

2018-02-19 21:58 UTC, apevec requested changes

2018-02-19 21:58 UTC, apevec commented on openvswitch.spec
> +Requires(post): sed
Linked bz resolved this with:
-Requires(post): /usr/bin/sed
+Requires(post): /bin/sed
which works in both Fedora and RHEL.

2018-02-20 08:35 UTC, hguemar commented
```bash
[vagrant@mine ~]$ rpm -q --whatprovides /usr/bin/sed
sed-4.2.2-5.el7.x86_64
[vagrant@mine ~]$ repoquery --whatprovides /usr/bin/sed
```
Just for fun on a centos vagrant image ...

2018-02-20 08:35 UTC, merged